version: "3.7"
services:
  app:
    build:
      args:
        user: pikachu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pokemon
    container_name: pokemon-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pokemon
  mysql:
    image: mysql:5.7
    container_name: pokemon-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - pokemon
  nginx:
    image: nginx:1.17-alpine
    container_name: pokemon-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - pokemon
networks:
  pokemon:
    driver: bridge
